windows/hid.c

Modern Windows implementations don't allow opening HID devices in
READ/WRITE mode if they are claimed by the system.  Examples of such
devices include keyboards and mice.
However, these devices can be opened without READ/WRITE permissions, in
order to allow sending and receiving feature reports.
If open_device() fails, retry without requesting READ/WRITE permissions.
This inverts the logic of the parameter to open_device().
It is a refactor of #44 by @pqu.
Signed-off-by: Sean Cross <sean@xobs.io>
Re-open of signal11/hidapi#335

windows: retry open_device() without r/w if it fails

---

configure.ac

The += operator is bashism and won't work with non-bash shells, such as
ash on Alpine Linux.

configure.ac: don't use +=

---

windows/hid.c

Right now, in hid_open it is checked if the connected devices have
"HIDClass" driver name. This is true for composite devices, but some
simple HID devices only have "Mouse" or "Keyboard" driver name.
One of devices that cannot be opened is Dell MS116t, but any mouse which
is not part of composite device can be affected.
With this change, one can enumerate and open these devices.
Signed-off-by: Kubicz, Filip <filip.kubicz@nordicsemi.no>

Windows: enumerate simple devices

---

README.txt

FreeBSD support was added in commit 74440e2d as the fifth back-end, but
the list was still introduced as "HIDAPI has four back-ends."

README.txt: update number of backends

---

Makefile.am

The 'make' build on Linux/MacOS generates an error since README.txt was renamed to README.md. See #17 .

Update Makefile.am after README.md

---

doxygen/Doxyfile
hidapi/hidapi.h
libusb/hid.c
mac/hid.c
windows/hid.c

The first commit is auto-generated with `doxygen -u`
The second commit fixes most of the doc generation being wrong, because the "relative indentation" in hidapi.h comments was being intepreted as codeblocks. 
The third commit fixes a warning because in the hid_read_timeout documentation the parameter-name "device" was used but the function used "dev". As all other functions use "device", adjust the function.

Fix documentation generation

---

README.md

* Markdown fixes.
* Table of contents

README: Add table of contents & fix markdown

---

hidapi/hidapi.h

Wrong struct called out
Originally https://github.com/signal11/hidapi/pull/409

Fix doc string for hid_enumerate

---

libusb/hid.c
linux/hid.c
mac/hid.c

Fix compilation without -fpermissive
Originally was PR https://github.com/signal11/hidapi/pull/430

Explicit cast from void* to corresponding type

---

.gitignore

This should result in no untracked files being present in the working directory when `./bootstrap` was run

Add ar-lib & compile to .gitignore

---

libusb/hid.c

```
hid.c:458:18: warning: passing 'const char **' to parameter of type 'char **' discards qualifiers in nested pointer types
[-Wincompatible-pointer-types-discards-qualifiers]
res = iconv(ic, &inptr, &inbytes, &outptr, &outbytes);
^~~~~~
/usr/local/include/iconv.h:85:43: note: passing argument to parameter 'inbuf' here
extern size_t iconv (iconv_t cd,  char* * inbuf, size_t *inbytesleft, char* * outbuf, size_t *outbytesleft);
^
1 warning generated.
```
I'm not sure why this `#ifdef` existed but it compiles fine on FreeBSD 12 with this change (and gets rid of the warning).

Fix compile warning on FreeBSD

---

linux/hid.c

Also drop HIDIOC* definitions as they are present since kernel 2.6.39.

linux: Drop workaround for kernel < 2.6.34

---

hidapi/hidapi.h
libusb/hid.c
linux/hid.c
mac/hid.c
windows/hid.c

Here is my first try at implementing error messages for the Linux/hidraw implementation.
* I used a thread-local variable for non-device error messages.
* Non-device errors can be obtained by passing `NULL` into `hid_error` as I suggested in #123.
* I **belive** to have covered all system calls that could fail; please check this.
A few extra questions:
* I am not sure why in `utf8_to_wchar_t` the input is called `utf8`. As far as I know, the encoding used in `mbstowcs` depends on the current locale, if if I haven't set my locale to use UTF8, then the input is not UTF8.
* The `register_error` equivalent in `windows/hid.c` doesn't use its argument `const char *op`. Is that intended?
* In the Windows implementation, do functions like …

hidraw: Implement hid_error()

---

.appveyor.yml
windows/.gitignore
windows/hidapi.sln
windows/hidapi.vcxproj
windows/hidapi.vcxproj.filters
windows/hidtest.vcxproj
windows/hidtest.vcxproj.filters

This PR also contains "Upgrade Windows projects to VS2015", originally signal11/hidapi#324 (but `hidtest.cpp` replaced with `hidtest.c`) as the old project file format is not compatible with Visual Studio 2015 (the Visual Studio version appveyor uses).
@Qbicz has changes for 64-bit builds, that should be integrated as well I think (and then the CI script changed to build both)

Add Windows (msbuild & cygwin) CI

---

testgui/mac_support_cocoa.m

The first commit should be backwards compatible (< 10.12), as I've added a define for the old type.
The second commit I'm not sure about, from what I could fine it was an API change in NSApplication in macOS 10.10, so it might not compile on versions before that?

testgui: fix compile warnings on macOS

---

linux/hid.c
mac/hid.c

This fixes an uninitialized usage_page value leaking from the Linux
backend. It may fix other uninitialized values, too.

Zero-initialize new hid_device_info structs

---

.builds/freebsd.yml
configure.ac

Works fine on FreeBSD 12, not tested on kFreeBSD but it should work fine there too.
Patch taken from the NetBSD ports, the patch was added to the CVS by `nia` which seems to be Nia Alarie according to https://www.netbsd.org/people/developers.html and I've found an email address at https://git.qemu.org/?p=qemu.git;a=commit;h=f7f5398dc76685a33e4effe477bf12aaf5fc8bc8 . Should I change the author of the commit to this name+email?

configure.ac: Use pkg-config to find libusb on *freebsd

---

mac/hid.c

On MacOS, a `calloc()` is made but isn't freed in the event the HID manager doesn't initialize properly.

Prevent memory leak in hid_open_path() if hid_init() fails

---

mac/hid.c

same as in hid_send_feature_report, and Windows/Linux

macOS: send report id conditionally for hid_get_feature_report

---

dist/hidapi.podspec

Unfortunately I made a mistake in podspec. For some reason validation (`pod spec lint`) worked, but I tried to use podspec using `pod 'hidapi', :podspec => 'https://github.com/libusb/hidapi/raw/master/dist/hidapi.podspec'` without success, because of tag names.
This PR has to fix the issue

Fixed tag name for hidapi releases

---

windows/hid.c

Fix for unusual cases where the hardware does not return the name and the string is not initialized at all.

Fix for wrong text on Windows on unusual cases

---

README.md

In response to https://github.com/libusb/hidapi/issues/105

README: Add warning about writing data to HID products

---

hidapi/hidapi.h
libusb/hid.c
linux/hid.c
mac/hid.c
windows/ddk_build/hidapi.def
windows/hid.c

This was tested for all operating systems and each worked identically.

Added support for Get Input Report to linux, mac, windows and libusb.

---

hidtest/test.c
mac/hid.c

Update of @fengji2006 PR#65, second try.
I think this includes all the requested changes, on top of the work done by @fengj2006 on https://github.com/libusb/hidapi/pull/65. Unlike the previous attempt, I think this doesn't regress the other recent changes made.
You can now see all the different usages as different "devices" in `hid_enumerate()`.  When running `hidtest` you see them too.  On a Macbook Pro with internal keyboard/trackpad, there are many:
```
% ./hidtest | grep -E "(Product|Usage)"
Product:      Apple Internal Keyboard / Trackpad
Usage (page): 0x3 (0xff00)
Product:      Apple Internal Keyboard / Trackpad
Usage (page): 0xd (0xff00)
Product:      Apple Internal Keyboard / Trackpad
Usage (page): 0x2 (0x1)
Product:      Apple Internal Keyboard / Trackpad
Usage (page): 0x1 (0x1) …
```

macOS support for multiple usage/usage-pages

---

mac/hid.c

The referenced location of IOKit framework is wrong.
See https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/OSX_Technology_Overview/SystemFrameworks/SystemFrameworks.html for details.

macOS: IOKit framework location corrected.

---

libusb/hid.c

Support for pthread_barrier was introduced in Android 7, so trying to build a custom implementation of that clashes with the system headers.

Fix build when targeting Android 7 or later

---

windows/hid.c

Older versions of MSVC (for example when using Visual Studio 10) don't yet support variable declaration in the middle of blocks:
```
hidapi\windows\hid.c(845) : error C2275: 'BOOL' : illegal use of this type as an expression
C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include\windef.h(153) : see declaration of 'BOOL'
```
Move the declaration of `res` to the beginning of the function.  Like in `hid_get_feature_report`, only `res` is moved, essentially ignoring the `#if 0` block (or assuming it will never be enabled).
---
Fixes: 083223e77952 ("Added support for Get Input Report")
Downstream issue: trezor/cython-hidapi#81 ("WIP: Fix build issues on AppVeyor")

Move local variable declaration to the beginning of the function

---

Makefile.am
configure.ac
libusb/Makefile-manual
libusb/Makefile.am
libusb/Makefile.haiku

Relevant issue: #140
This proposal will add support for the [Haiku](https://haiku-os.org) operating system out of the box. A decent bunch of software depends on `hidapi` already, and pushing these changes to the upstream version of the codebase would greatly assist with maintainability on our end.
The patches were originally written by @CodeforEvolution (although for an older version), hence the commit has been made under their behalf.
@Begasus's tree (which had applied the patches already) was used as a base for this proposal, for the sake of simplicity: https://github.com/Begasus/hidapi/tree/haiku

Changes to Build System for Haiku

---

testgui/copy_to_bundle.sh

Otherwise hidapi-testgui will be put at TestGUI.app/Contents/MacOS which
results in a malformed .app structure.
The following build combinations have been tested:
* 'make -f Makefile-manual' with libtool
* 'make -f Makefile-manual' without libtool
* './configure --enable-testgui && make'
Fixes #151

testgui: ensure $EXEPATH is a directory

---

mac/hid.c

The compiler provided the following warning message:
```
hid.c:830:29: warning: format specifies type 'void *' but the argument has type 'IOHIDDeviceRef' (aka 'struct __IOHIDDevice *') [-Wformat-pedantic]
sprintf(str, "HIDAPI_%p", dev->device_handle);
~~   ^~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/secure/_stdio.h:47:56: note: expanded from macro 'sprintf'
__builtin___sprintf_chk (str, 0, __darwin_obsz(str), __VA_ARGS__)
```

Fix compilation warning in pedantic mode on macOS

---

windows/hid.c

This patch applies an explicit cast to function parameters which are supplied as size_t type and which need to be passed to the Windows API functions requiring a DWORD type parameter.  Microsoft's compiler complains if this cast is not performed.
There are two cases in `hid_read_timeout` and `hid_send_feature_report` where the hidapi function signature requires an int as a return type, but the lengths being returned are internally calculated using size_t type.

FIX Compiler Warnings on Windows

---

windows/hid.c

- Implemented solution from issue signal11/hidapi#88
- Allows read/write frames up to 1000 per second

Windows Handle GetOverlappedResult blocking on read/write fix (#128)

---

configure.ac
mac/Makefile-manual
mac/hid.c

In one of the early versions of macOS, when you try to close the device
with IOHIDDeviceClose() that is being physically disconnected.
Starting with some version of macOS, this crash bug was fixed,
and starting with macSO 10.15 the opposite effect took place:
in some environments crash happens if IOHIDDeviceClose() is _not_ called.
This patch is to keep a workaround for old versions of macOS,
and don't have a leak in new/tested environments.
Fixes: #144.

Don't leak device handle in macOS 10.10 or newer

---

windows/hid.c

Currently trying to call `hid_open` on a device that doesn't have a serial number will result in a crash in the call to wcscmp here. Check that it's not null before calling wcscmp.

MSVC: crash bugfix when trying to open device without a serial number

---

mac/hid.c

It improves backward compatibility with versions of hidapi, where
usage/usage_pairs didn't emit seaprate hid_devices_info.

macOS: enumerate device with primary usage/usage_page first

---

libusb/hid.c

Read callback may fire itself on its own even after its been
requested to stop and exactly before the calling code
waits for its completion in indefinite loop.
Explicitly preventing re-fireing the submission loop,
fixes the issue.
Fixes: #142.
Signed-off-by: Ihor Dutchak <ihor.youw@gmail.com>

libusb: fix race condition on device close

---

linux/hid.c

The open systcall is allowed to return 0 as a valid file descriptor,
and considering it an error breaks environments where unnecessary
fds are closed before executing untrusted processes.
Fixes: #199
Signed-off-by: Marc Zyngier <maz@kernel.org>

linux/hidraw: Don't consider open returning 0 as an error

---

mac/hid.c

Removes a possible cause for a segmentation fault observed in `CFSetGetCount` (see #208).
Note: completely untested (no access to a mac right now).

macOS: check if IOHIDManagerCopyDevices returned a NULL

---

hidapi/hidapi.h

With gcc 10.2.0 and compile flag '-Wstrict-prototypes' the new
APIs in hidapi.h trigger a compile warning:
../hidapi/hidapi.h:481:32: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
481 |   HID_API_EXPORT const  struct hid_api_version* HID_API_CALL hid_version();
|                                ^~~~~~~~~~~~~~~
../hidapi/hidapi.h:491:3: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
491 |   HID_API_EXPORT const char* HID_API_CALL hid_version_str();
|   ^~~~~~~~~~~~~~
To replicate:
./bootstrap
CFLAG=-Wstrict-prototypes ./configure
make
This is an issue for other projects, like OpenOCD, that use hidapi
and compile by default with '-Wstrict-prototypes -Werror'; the
warning above causes compile error while including hidapi.h.
Fix the prototypes by …

hidapi.h: fix API prototype for gcc flag -Wstrict-prototypes

---

windows/hid.c

Type cast that works with more configurations of Visual Studio.  Enables building out of the box with the standard vrpn.dsw file from github.com/vrpn/vrpn.
The more-specific cast works with both the CMake version and the stock solution file.  The more general LPVOID cast worked with CMake but failed with the stock file.

More specific pointer cast to work in all build environments

---

linux/hid.c

- uhid USB, Bluetooth (standard) and I2C now enumerating
* USB uhid support was added by removing the udev USB endpoint check
- HID over I2C was excluded before (likely because it didn't exist when
hidraw was developed)
I'm still looking for a device with HID over I2C (I have one
somewhere...). For now I've tested that code path using uhid instead.
Device Found
type: 308f 0030
path: /dev/hidraw14
serial_number: uhid virtual
Manufacturer:
Product:      HID-IO Virtual Keyboard - Standard USB
Release:      0
Interface:    -1
Usage (page): 0x6 (0x1)
Device Found
type: 308f 0030
path: /dev/hidraw17
serial_number: uhid virtual
Manufacturer:
Product:      HID-IO Virtual Keyboard - Standard I2C
Release:      0
Interface:    -1
Usage (page): 0x6 (0x1)

Adding support for HID over I2C and uhid devices

---

windows/hid.c

`HidD_SetFeature()` requires a feature report be at least a certain size similar to the requirement for `WriteFile()` in the implementation of `hid_write()`.

Windows: ensure buffer passed to HidD_SetFeature is large enough

---

configure.ac

fixes build with autoconf 2.70

configure.ac: remove duplicate AC_CONFIG_MACRO_DIR

---

windows/hid.c

Based on
https://github.com/microsoft/Windows-driver-samples/blob/master/hid/hclient/pnp.c#L32
Fixes wrong detection of the class of devices.
Fixes: #234

Windows: Fix devices enumeration

---

configure.ac

Hello!
Build currently does not work under MSYS2, because it does not have it as an option for host OS in the configure script.
It is the same as MinGW, so I just copy-pasted that to a string which would be recognized under MSYS2.

Added support for MSYS2

---

libusb/hid.c
linux/hid.c
mac/hid.c
windows/hid.c

This is my proposed solution for avoiding a macOS panic in `set_report` when the user supplies a zero length buffer (indicated by either a NULL data or a length of 0 or less).
Looking back at the source, I see that `length` is of type `size_t` which my foggy brain remembers being unsigned so the test for `less than or equal to zero` should likely be `equal zero`. 
Fixes: #278

Guard against zero length buffers in hid_write

---

windows/hid.c

This fixes https://github.com/libusb/hidapi/issues/229

hid_get_input_report: Correct number of bytes_returned

---

windows/hid.c

This originally tested/confirmed by @mcuee.
Confirmed the expected behavior by Tim Roberts https://sourceforge.net/p/libusb/mailman/message/37303650/.

win: hid_get_feature_report: Correct number of bytes_returned

---

libusb/hid.c

format the path like the linux kernel does:
<busnum>-<port[.port]>…:<config num>.<interface num>
See also https://github.com/libusb/hidapi/pull/117
Closes: #117

libusb backend: stabilize device path, superseeds: #117

---

windows/hid.c

In some cases HidD_GetSerialNumberString/HidD_GetManufacturerString/HidD_GetProductString can fail.
For example if we have Bluetooth LE gamepad on Windows.
In this case we are currently returning not initialized strings in `hid_device_info`.

Fix possible garbage in device strings returned from hid_enumerate()

---

windows/hid.c

Cleanup Windows backend code a bit before adding HID device connection callback code.

Cleanup Windows backend code a bit

---

windows/hid.c

Fix issue #289 that there is a compiler warning when using MSYS2 MinGW-w64 compiler. 
```
[ 25%] Building C object src/windows/CMakeFiles/hidapi_winapi.dir/hid.c.obj
In function 'hid_get_device_info',
inlined from 'hid_enumerate' at C:\work\hid\hidapi\windows\hid.c:517:34:
C:\work\hid\hidapi\windows\hid.c:333:3: warning: 'strncpy' specified bound depends on the length of the source argument [-Wstringop-overflow=]
333 |   strncpy(dev->path, path, len + 1);
|   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:\work\hid\hidapi\windows\hid.c: In function 'hid_enumerate':
C:\work\hid\hidapi\windows\hid.c:331:16: note: length computed here
331 |   size_t len = strlen(path);
|                ^~~~~~~~~~~~
$ gcc -v
Using built-in specs.
COLLECT_GCC=C:\msys64\mingw64\bin\gcc.exe …
```

Update hid.c to fix MSYS2 MinGW-w64 compiler warning

---

mac/hid.c

With some device connection configurations,
the device paths become over 512 bytes (io_string_t max length)
which makes them unusable with current implementation.
Rather than using ServiceRegistry string path, use its ID,
which is uint64_t and easily serializable/deserializable into a string.
Implementation idea by felix.schwarz@iospirit.com
https://github.com/flirc/hidapi/commit/8d251c3854c3b1877509ab07a623dafc8e803db5
Fixes: #127, #236.

macOS: use IORegistryEntryGetRegistryEntryID to resolve paths

---

windows/hid.c

This PR fixes issue with empty `manufacturer_string`/`product_string`/`serial_number` in `hid_device_info` struct with Bluetooth LE devices on Windows systems.
Fixes: #282

RFC: Bluetooth LE device info on Windows

---

udev/69-hid.rules

As recently discovered (thanks @tresf), the `TAG+="uaccess"` has to be used
before `73-seat-late.rules` and not before `70-uaccess.rules`.
Technically it doesn't harm, to have a more restrictive recommenration,
but it was not technically currect.
Refference on `uaccess` TAG consumption:
[1](https://github.com/systemd/systemd/blob/3a1220eedfb65355c387c29584380742a21917aa/src/login/73-seat-late.rules.in), [2](https://www.apt-browse.org/browse/debian/wheezy/main/amd64/systemd/44-11+deb7u4/file/lib/udev/rules.d/73-seat-late.rules).
Relates to: #276, systemd/systemd/issues/4288.

udev.rules documentation improvement

---

.github/workflows/builds.yml
AUTHORS.txt
libusb/CMakeLists.txt
libusb/Makefile.am
libusb/hid.c
libusb/hidapi_libusb.h

Rationale: on Android one must use UsbManager, to access any
USB device. As a result, libraries like libusb can only use file descriptors
that are provided by UsbManager.
libusb has an API to use such file descriptors: hid_libusb_wrap_sys_device.
Having hid_libusb_wrap_sys_device currently is the only way to make hidapi
work on Android without root access and without custom Android builds.
Relevant info: https://github.com/libusb/libusb/pull/830/files

add libusb-specific hid_libusb_wrap_sys_device

---

.gitignore
windows/hid.c

- It appears when the numbered reports aren't used,
WinAPI returns size of the report excluding the data[0] which contains 0,
as an indication that numbered reports aren't used;
Explicity count that byte in the result.
Fixes: #328

Windows: hid_get_feature/input_report return size fix

---

libusb/CMakeLists.txt
src/CMakeLists.txt

Otherwise it is impossible to `#include <hidapi_libusb.h>`,
when HIDAPI is added directly as a subdirectory of a CMake project.

Add <root>/libusb to includes for in-tree build

---

windows/hid.c

Seems to be introduced in https://github.com/libusb/hidapi/pull/309/
```
2021-11-10T00:31:43.7352733Z hid.c:164:83: error: unknown type name ‘DEVPROPKEY’
2021-11-10T00:31:43.7355003Z   typedef CONFIGRET(__stdcall* CM_Get_DevNode_PropertyW_)(DEVINST dnDevInst, CONST DEVPROPKEY* PropertyKey, DEVPROPTYPE* PropertyType, PBYTE PropertyBuffer, PULONG PropertyBufferSize, ULONG ulFlags);
```

windows: add missing include for mingw32

---

linux/hid.c

Fixes https://github.com/libusb/hidapi/issues/259

implement hid_get_input_report for Linux hidraw backend

---

libusb/hid.c

In case if libusb_detach_kernel_driver fails inside hidapi_initialize_device
HIDAPI had tried to `libusb_close(dev->device_handle)` two times:
- right after `libusb_detach_kernel_driver`;
- outside of `hidapi_initialize_device` function;
The fix: `libusb_close` the device only once.
And since `hidapi_initialize_device` is not responsible for opening the device -
it is not responsible for closing it either.

Fix potential crash when libusb_detach_kernel_driver fails

---

configure.ac
testgui/Makefile.mingw
testgui/testgui.vcproj
windows/CMakeLists.txt
windows/Makefile.mingw
windows/hid.c
windows/hidapi.vcproj
windows/hidapi.vcxproj

- Ported code from SetupApi to CfgMgr32. See: https://docs.microsoft.com/windows-hardware/drivers/install/porting-from-setupapi-to-cfgmgr32
- Use Unicode Windows API internally where possible. Windows operates natively in UTF-16 (WCHAR) so do we too.

Ported code from SetupApi to CfgMgr32

---

windows/hid.c

Don't pass invalid pointers to HidD_FreePreparsedData in hid_open_path
Fixes a segfault that happens when hid_open_path is called on a previously disconnected device.
This is a regression caused by:
b600727 - Win32: Fix memory leak in `free_hid_device` (#361)

Win32: hid_open_path hotfix

---

mac/hid.c

Fixes the following warnings (or in our case errors when building with `-Werror`):
```
hid.c:420:45: error: variable 'entry_id' may be uninitialized when used here [-Werror,-Wconditional-uninitialized]
sprintf(cur_dev->path, "DevSrvsID:%llu", entry_id);
^~~~~~~~
In module 'Darwin' imported from hid.c:30:
/Applications/Xcode-13.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk/usr/include/secure/_stdio.h:47:56: note: expanded from macro 'sprintf'
__builtin___sprintf_chk (str, 0, __darwin_obsz(str), __VA_ARGS__)
^~~~~~~~~~~
hid.c:384:19: note: initialize the variable 'entry_id' to silence this warning
uint64_t entry_id;
^
= 0
hid.c:908:10: error: implicit conversion loses integer precision: 'size_t' (aka 'unsigned long') to 'int' [-Werror,-Wshorten-64-to-32] …
```

Fix possible warnings on macOS

---

mac/CMakeLists.txt
mac/hid.c
mac/hidapi_darwin.h

As discussed in https://github.com/libusb/hidapi/discussions/252#discussioncomment-2089707.
Not sure if there’s a simpler way to do this, but as I need the location ID during enumeration it seems I first need to create a `IOHIDDeviceRef` from the path in order to get the location ID.

Add Mac-specific API to get device location ID

---

mac/hid.c
mac/hidapi_darwin.h

darwin: add option to open device in non-exclusive mode

---

libusb/hid.c

In hid_close() buffer pointer is freed and next to that the
libusb_free_transfer function is called which checks for if
the LIBUSB_TRANSFER_FREE_BUFFER flag is set and the buffer
pointer is not NULL. when this condition evaluates true, it
tries to free memory for a buffer which is already free and
a crash occurs.
Make buffer pointer NULL, once it is freed.

libusb: Fix double free of buffer pointer in hid_close()

---

src/CMakeLists.txt
src/cmake/hidapi-config.cmake.in

- FindPkgConfig.cmake warns it is not called by find_package;
- CMake package `config` file and `exports` file names should not match,
otherwise it gets included recursively by GLOB expression;

Fix find_package(hidapi) warnings

---

mac/hid.c

`kIOMasterPortDefault` is deprecated since macOS 12.0.
One alternative is to use named constant `kIOMainPortDefault` which is not available before macOS 12.0.
Both named constants are just an alias for `NULL`, so it is simpler to use it directly instead.
Fixes: #377

Don't use deprecated kIOMasterPortDefault

---

windows/hid.c

code segment (from: [hidtest](https://github.com/libusb/hidapi/blob/master/hidtest/test.c)):
```C
#define MAX_STR 255
wchar_t wstr[MAX_STR];             // !!! <----- wstr[255]; 0~254;
// Read the Manufacturer String
wstr[0] = 0x0000;
res = hid_get_manufacturer_string(handle, wstr, MAX_STR);
int HID_API_EXPORT_CALL HID_API_CALL hid_get_product_string(hid_device *dev, wchar_t *string, size_t maxlen)
{
if (!dev->device_info)
{
register_string_error(dev, L"NULL device/info");
return -1;
}
if (!string || !maxlen)
{
register_string_error(dev, L"Zero buffer/length");
return -1;
}
wcsncpy(string, dev->device_info->product_string, maxlen);
string[maxlen] = L'\0';      // !!! <----- string[255] = L'\0'; boom!
// fixed: string[maxlen - 1] = L'\0';
return 0;
}
```

Fix: memory write out of bounds. (windows)

---

hidapi/hidapi.h
hidtest/test.c
libusb/hid.c
linux/hid.c
mac/hid.c
windows/hid.c

Resolves: #431
Closes: #164
Closes: #163
I don't like the signature of `get_device_info_for_device` in linux, and Im unsure about `fill_device_info_for_device` in libusb.
The mac, linux and libusb implementations appear to work fine with hidtest.
I havent tested the other backends yet

Add hid_get_device_info

---

libusb/hid.c

Potential execution path may happen if kernel driver successfully detached,
but libusb failed to claim the requested interface.
Otherwise the device remains with detached kernel driver.

Reattach kernel driver when failed to claim interface

---

hidtest/test.c

Avoid infinite reading from the device if the device doesn't send any interrupt reports.
Otherwise hidtest has to be stopped by Ctrl+C interruption, which doesn't give a chance to close the device properly,
as a result this has negative side-effects when using LIBUSB backed.

Run hidtest for no more than 10 seconds when no hid_read data

---

libusb/hid.c

A small bug introduced by #432.

libusb: fix enumerating device path w/o root access

---

linux/hid.c

In general, `open()` should always be called with `O_CLOEXEC`, except immediately before an `exec*` call that will use the fd.
Previously the fd was leaked to a child process, as seen here:
```c
int main() {
assert(hid_open_path("/dev/hidraw0") > 0);
char *args[] = {"/bin/sh", "-c", "readlink /proc/self/fd/*", NULL};
execve("/bin/sh", args, NULL);
}
```
In some cases this could be a security issue if child processes may be less privileged and shouldn't have access to the file.

linux: Open files with `O_CLOEXEC` to not leak fds to child processes

---

.builds/openbsd.yml

NOTES, as described in https://github.com/libusb/hidapi/pull/31:
- it is still not easy to use HIDAPI on OpenBSD since it is not easy to use LIBUSB to replace the HID driver;
- there is a name colision with `hid_init` from [`usbhid`](https://man.openbsd.org/usbhid.3) OpenBSD library;
Closes: https://github.com/libusb/hidapi/pull/31

CI: add OpenBSD compilation test

---

hidapi/hidapi.h
libusb/hid.c
linux/hid.c
mac/hid.c

- first step is to use HID_API_MAX_REPORT_DESCRIPTOR_SIZE internally;
- port a few improvements from get-descriptor branch early;

Introduce HID_API_MAX_REPORT_DESCRIPTOR_SIZE

---

libusb/hid.c

- When `libusb_submit_transfer` in `read_thread` fails, `read_callback` never gets called and never sets `transfer_loop_finished` to true, causing `read_thread` to loop indefinitely.
- Fix this by skipping the handle_events for the transfer
- Fixes #456

libusb: stop `read_thread` from looping indefinitely (#456)

---

.gitignore
libusb/hid.c
mac/hid.c

This PR:
- resolves the merge conflict
- Adds two register_device_error statements for hid_get_report_descriptor on mac

Merge changes from master into get-descriptor branch

---

README.md

When no device is connected (or user doesn't have permission to access
device), hid_open returns NULL.  If NULL is passed to
hid_get_manufacturer_string(), it crashes with SIGSEGV, which could be
confusing to newcomers trying to get example to work.
wprintf and printf aren't compatible in the same stream
Now it's more similar to https://github.com/libusb/hidapi/blob/master/hidtest/test.c#L129
Closes: #469

README example: prevent segmentation fault and mixture of printf/wprintf

---

configure.ac

When compiling a 32bit dll with the mingw-w64 compiler, some 64bit integer arithmetic operations are implemented using functions from libgcc (e.g. __udivdi3 and __umoddi3 from libgcc_s_dw2-1.dll). This unexpected dependency is inconvenient for applications.
The run-time dependency can be avoid by linking statically.

Link gcc helpers statically on MinGW

---

linux/hid.c

This adds (or more accurately completes, since it was already started) support for HID over SPI devices. 
Handling is almost identical to HID over I2C.

Add support for HID over SPI

---

.github/workflows/builds.yml

The old versions are deprecated due to usage of Node.js 12.

Upgrade checkout and file-existence-action actions

---

windows/pp_data_dump/pp_data_dump.c

I built the get-descriptor branch with the clang-cl compiler for Windows and got some formatting warnings.
This PR contains the fixes for these warnings.

Fix formatting warnings from clang_cl

---

windows/hidapi_descriptor_reconstruct.c

Hello @JoergAtGithub and @Youw, First off, thank you both for your work on supporting reading/reconstructing report descriptors within this hidapi get-descriptors branch. It has been helpful for a project I've been working on.
I believe I've found a few small errors on windows within the reconstruction process that I'm submitting for your review and consideration merging back to the main hidapi repository. Thank you in advance for your attention.
The first commit is simply a null pointer test, which may be irrelevant now that I'm successfully sorting collection bit ranges, but harmless to include and might future proof other problematic cases. 
The second commit contains two changes: 
1. The sorting of child collections based on bit ranges was not working properly for me while testing …

Get descriptor (windows fixes)

---

hidapi/hidapi.h
windows/CMakeLists.txt

Don't mark API functions with `__declspec(dllexport)` when building a static library on Windows.
Enforced by CMake builds.
For other builds a compile definition is available.
Related: #480

windows: don't mark with dllexport in static build

---

libusb/hid.c

When hid_enumerate() iterates over the device list, it's possible that libusb_open() fails. If this occurs on the next round after a successful libusb_open() call, create_device_info_for_device() is passed the previous iteration's already closed device handle.
Fix the crash by setting the handle to NULL after libusb_close().

libusb: fix crash in hid_enumerate() caused by a stale device handle

---

hidtest/test.c
mac/hid.c

macos: improve USB interface number retrival

---

windows/hidapi_descriptor_reconstruct.c
windows/test/hid_report_reconstructor_test.c

Fix Coverity issues  CID1530052, CID1530054, CID1530055

---

mac/hid.c

Return from hid_open_path early in case if hid_init fails to avoid crash

---

windows/hidapi_descriptor_reconstruct.c
windows/hidapi_winapi.h

This fixes build warnings with -Wdocumentation (and build failures if your build has warnings as errors enabled)

Fixed parameter documentation mismatch

---

libusb/hid.c
libusb/hidapi_thread_pthread.h

This isn't a full Windows or macOS port, but abstracts the libusb threading code so that it can be easily ported to other platforms.
Fixes https://github.com/libusb/hidapi/issues/581

libusb: Allow building using non-POSIX runtime

---

libusb/hid.c

This is important if libusb and hidapi have been built with different calling conventions

hidapi/libusb: use LIBUSB_CALL for the read_callback function

---

mac/hid.c

There's a macOS bug with some devices where string properties aren't actually strings, and this prevents a crash when this happens. Specifically we ran into this with Apple AirPods.

hidapi/mac: fixed crash on macOS when AirPods are connected

---

libusb/hid.c

This guarantees that we have the same set of paths in the open that we do when enumerating devices.

hidapi/libusb: use the same logic to get the config descriptor in hid_open_path() as in hid_enumerate()

---

AUTHORS.txt
BUILD.cmake.md
libusb/CMakeLists.txt
libusb/hid.c
linux/hid.c
mac/hid.c
udev/69-hid.rules
windows/hid.c
windows/hidapi_descriptor_reconstruct.c
windows/test/hid_report_reconstructor_test.c

Found via `codespell -q 3 -L childs,fo,xwindows`
Encountered in downstream https://github.com/libsdl-org/SDL

Fix various typo

---

libusb/hid.c

Xbox controllers are not technically HID devices, but you can talk to them directly using libusb, and [SDL](https://github.com/libsdl-org/SDL) uses this to talk to controllers which may not have OS-level support.

hidapi/libusb: enable support for Xbox 360 and Xbox One controllers

---

.github/workflows/builds.yml

- don't use `--rerun-failed` - it only makes sense on subsequent runs of the test, when checking of failed tests got fixed;
- add `--no-compress-output` - to avoid stripping test's output of failure;

Refine CTest args

---

.github/workflows/builds.yml

Apparently when installing/upgrading packages on Archlinux - need to explicitly make sure `glibc` is upgraded as well.
Fixes: #607

CI: Fix Archlinux build

---

libusb/hid.c
linux/hid.c

To be consistent with Windows/macOS (OS-level implementations).
Fixes: #298
Fixes: #454

hidraw: report only Top-Level Usage_page/Usage pairs as 'unique' devices 

---

configure.ac
dist/hidapi.podspec
mac/CMakeLists.txt
mac/Makefile-manual
mac/hid.c

macOS: Check for macOS 10.10 using kCFCoreFoundationVersionNumber instead of AppKit

---

libusb/hid.c

If a device has multiple altsettings, like an Xbox Series X controller, make sure we only enumerate each interface once, not once for each altsetting.

Only enumerate each interface once

---

mac/hid.c

This function is called with a literal NULL for that pointer later in the file.
We had a user run into this in SDL; checking for NULL before memcpy()'ing resolved it.

Don't try to memcpy() to a NULL destination.

---

src/CMakeLists.txt

If `HIDAPI_INSTALL_TARGETS` is set to off, pkgconfig is still installed. This a problem when statically linking against libhid and then using CMake's install-feature.

CMake: Do not install pkgconfig

---

.github/workflows/builds.yml
hidtest/test.c
libusb/hid.c
windows/hidapi_descriptor_reconstruct.h
windows/pp_data_dump/pp_data_dump.c
windows/test/hid_report_reconstructor_test.c

This merge-request removes the need for 
```C
#pragma GCC diagnostic ignored "-Wformat"
#pragma GCC diagnostic ignored "-Wformat-extra-args"
```
in mingw. It also turns on `-Wformat-signedness` for GNU-compatible compilers.
This fixes #632

Fix the windows build by fixing printf related issues

---

windows/hid.c

Win32 HID API doc says: For USB devices, the maximum string length is 126 wide characters (not including the terminating NULL character).
For certain USB devices, using a buffer larger or equal to 127 wchars results in successful completion of HID API functions, but a broken string is stored in the output buffer. This behaviour persists even if HID API is bypassed and HID IOCTLs are passed to the HID driver directly (IOCTL_HID_GET_MANUFACTURER_STRING, IOCTL_HID_GET_PRODUCT_STRING, etc).
So, the buffer MUST NOT exceed 126 wchars.

windows: change MAX_STRING_WCHARS to 126

---

windows/hid.c

This is unsafe because the event is auto-reset, therefore the call to WaitForSingleObject() resets the event which GetOverlappedResult() will try to wait on.
Even though the overlapped operation is guaranteed to be completed at the point we call GetOverlappedResult(), it will still wait on the event handle for a short time to trigger the reset for auto-reset events. This amounts to roughly a 100 ms sleep each time GetOverlappedResult() is called for a completed I/O with a non-signalled event.
In the context of HIDAPI, this extra sleep means that callers that loop on hid_read_timeout() with timeout=0 will loop forever, since the 100 ms sleep each iteration ensures ReadFile() will always have new data.

hidapi/windows: do not wait in GetOverlappedResult() in hid_read_timeout()

---

hidtest/test.c
windows/hid.c

Windows hotplug: Mutex for callback actions

---

netbsd/hid.c
windows/hid.c

Just a small patch to ensure there are no undefined references on supported platforms.

Connection callback: add stubs for netbsd

---

hidtest/test.c
mac/hid.c

This is a ~~MOCK-UP of a~~ finalized but untested hotplug implementation for Mac OS. It has the entire structure already set up (callback list management, device cache, mutex - everything copied straight from Linux version), but may still have some issues with RunLoop and event processing, which I will not be able to resolve myself because of a total lack of any meaningful documentation.

MacOS Hotplug: connection-callback implementation for MacOS

---

libusb/hid.c

This warning shows up when building with libusb support using MSVC.
Upstreaming of https://github.com/libsdl-org/SDL/commit/1664ac4fcb395f14c16b738e071ec3a1b058cd7f
https://github.com/libsdl-org/SDL/pull/10199

hidapi: fix "conversion from 'size_t' to 'int', possible loss of data"

---

hidtest/test.c
libusb/hid.c
linux/hid.c
mac/hid.c
windows/hid.c

This PR provides a solution to the possible issues that happen when a register or de-register call is made from inside a callback. The way it works is the same for all platforms and is described below.
Resolves #673 
1) The mutex is made recursive, so it can be locked by the same thread multiple times
2) ~~The `mutex_ready` variable is renamed to `mutex_state`, it is no longer a boolean value, and the value of 2 in it now indicates that the mutex is "In Use" (locked by a function that calls a callback).~~ `mutex_ready` kept intact, added 2 more flags, `mutex_in_use` and `cb_list_dirty`.
3) ~~When the value of mutex_state is set to 2,~~ When the `mitex_in_use` flag is set, the Deregister call is no longer allowed to immediately remove any callbacks from the list. Instead, the `events` …

Deadlock prevention patch for Connection-callback feature

---

windows/hid.c

Return bytes_written in hid_write if WriteFile returns 1, which means it succeeded synchronously.
According to [documentation](https://learn.microsoft.com/en-us/previous-versions/troubleshoot/windows/win32/asynchronous-disk-io-synchronous), the system reserves the right to run WriteFile synchronously, even if FILE_FLAG_OVERLAPPED is set.
"Be careful when you code for asynchronous I/O because the system reserves the right to make an operation synchronous if it needs to. So it is best if you write the program to correctly handle an I/O operation that may be completed either synchronously or asynchronously. The sample code demonstrates this consideration."
Fixes #695

Windows: return bytes_written in hid_write if WriteFile returns 1 (succeeds synchronously)

---

libusb/hid.c
libusb/hidapi_libusb.h

This is initial implementation.
- hid_error is set correctly for most of the API functions;
- refactored iconv routines - common code for utf16 and utf8 to wchar_t implementation;
- `hid_libusb_error` to have libusb error code when possible;
Closes: #690
Fixes: #684

hid_error implementation for libusb

---

hidtest/test.c
windows/hid.c
windows/hidapi_winapi.h

Add API function to control hid_write timeout on WinAPI backend.
Resolves: #686

winapi: add hid_winapi_set_write_timeout

---

libusb/hid.c
windows/hid.c

- Do not call CloseHandle in hid_open_path if device_handle is NULL
- Return errors if malloc calls fail
- Return errors if calloc calls fail (new_hid_device returns NULL)

Add missing ptr checks after malloc/calloc calls

---

mac/hid.c

Found by Coverity: it appears `dev->last_error_str` never been freed on macOS.

Ensure last_error_str released on macOS

---

windows/hid.c
windows/hidapi_descriptor_reconstruct.c
windows/hidapi_hidclass.h

also make it work for older WINVER cases by copying a few defines
this is how we intend/want to use it within https://github.com/vpinball/vpinball, so would be nice to have that in the official repo

Make windows path compile for both C and C++ direct file include case

---

mac/CMakeLists.txt

As it used to be with autotools.
Fixes: #622

macOS: add option to mimic 1.0.0 compatibility version

---

hidapi/hidapi.h
hidtest/test.c
libusb/hid.c
linux/hid.c
mac/hid.c
netbsd/hid.c
windows/hid.c

hid_read_error is a separate error function, that returns error status of hid_read/hid_read_timeout.
hid_read/hid_read_timeout is no longer changes internal buffer used by hid_error and it makes it safe to use hid_read/hid_read_timeout from a separa thread, concurently with other device functions.
Closes: #688

Add hid_read_error

---

.github/workflows/builds.yml

Fix CI build on latest Archlinux with CMake 4.0
Fixes: #732

Fix Archlinux CI build

---

hidapi/hidapi.h
linux/hid.c
windows/hid.c

This driver implements a virtual HID device on linux: https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/tree/drivers/platform/x86/tuxedo/nb04/wmi_ab.c?id=cfd84b3f419bf0aec60ecddc92c61b539c339ec9#n841
This patch enables HIDAPI to handle this correctly.
Fixes: https://github.com/libusb/hidapi/issues/744

linux/hidraw: Add support for BUS_VIRTUAL
