- windows/hid.c
Signed-off-by: Kubicz, Filip <Filip.Kubicz@nordicsemi.no>
> windows: Fix undeclared variable name in register_error()

- configure.ac
Signed-off-by: Filip Kubicz <filip.kubicz@nordicsemi.no>
> configure.ac: Release 0.9.0-rc1

- configure.ac
Signed-off-by: Filip Kubicz <filip.kubicz@nordicsemi.no>
> configure.ac: release 0.9.0

- .builds/alpine.yml
- .builds/archlinux.yml
- .builds/fedora-mingw.yml
- .builds/freebsd.yml
- .travis.yml
This PR is for the platforms listed at #6 except Windows (msbuild & cygwin) as that needs an upgrade of the VS project to a newer version; see #12 
See also #15 
This would need configuration of https://dispatch.sr.ht and https://travis-ci.com/ on this repo.
> Add continuous integration config

- hidtest/hidtest.c
- libusb/hid.c
- linux/README.txt
- mac/hid.c
- testgui/copy_to_bundle.sh
- windows/hidtest.vcproj
> Misc. typo fixes

- README.md
Show status of test builds on the project GitHub page.
Fixes #35.
Signed-off-by: Filip Kubicz <filip@kubicz.engineer>
> README: add CI build badges

- libusb/hid.c
> Reattach kernel driver in hidapi-libusb

- .builds/alpine.yml
- .builds/archlinux.yml
- .builds/fedora-mingw.yml
- .builds/freebsd.yml
- .travis.yml
- libusb/Makefile.freebsd
- libusb/Makefile.linux
- linux/Makefile-manual
- mac/Makefile-manual
- windows/Makefile.mingw
> Fix manual Makefiles and add CI for them

- .cirrus.yml
Starting with Alpine and FreeBSD 11 and 12 tasks, others to be added.
Result from my fork: https://cirrus-ci.com/build/5686867601653760
> Add .cirrus.yml config for Cirrus-CI continuous integration

- .gitignore
- mac/hid.c
> macOS: fix -Wall -Wextra -pedantic compilation warnings

- hidtest/test.c
- libusb/hid.c
- linux/hid.c
> hidraw/libusb: fix -Wall -Wextra -pedantic -Werror compilation

- README.md
> Switch to libusb/hidapi appveyor project for badge

- .appveyor.yml
- windows/hidapi.vcxproj
- windows/hidtest.vcxproj
This change allows the code to compile without error when used in Visual Studio 2019.
> Use Conditional PlatformToolset projects for VS

- README.md
> Switch builds.sr.ht from ~qbicz to ~z3ntu

- libusb/hid.c
Relevant changes https://github.com/libusb/libusb/pull/874
> libusb: add support for potential Android JNI backend

- README.md
- udev/69-hid.rules
- udev/99-hid.rules
Refer to the commit messages for details.
> improve documentation for udev rule files on Linux

- windows/hid.c
> Whitespace cleanup in Windows implementation

- hidapi/hidapi.h
- hidtest/test.c
- libusb/hid.c
- linux/hid.c
- mac/hid.c
- windows/hid.c
- macOS implementation for it;
- stubs for all other platforms;
Closes #263
> add hid_get_report_descriptor API function

- .github/workflows/builds.yml
> Ubuntu CI: `apt update` before `apt install`

- windows/hid.c
> Fix sygwin compilation warnings

- BUILD.cmake.md
And its behavior, as controled by CMP0077.
Closes: #347
> Explicit remark about BUILD_SHARED_LIBS

- windows/hid.c
Strickly speaking we cannot parse interface string at all and only allowed to parse Hardware ID string.
> Parse USB interface number from device Hardware IDs.

- libusb/hid.c
- based on LIBUSB_REQUEST_GET_DESCRIPTOR/LIBUSB_DT_REPORT;
- improved logging of LIBUSB errors;
> libusb: add hid_get_report_descriptor implementation

- .appveyor.yml
- .github/workflows/builds.yml
- windows/hidapi.vcxproj
- windows/hidtest.vcxproj
- a straight-forward build matrix for Appveyor;
- MSBuild builds with Github Actions;
- Visual Studio 2022 support for `.sln` (toolset v143);
- gather Windows build artifacts with Github actions;
> Windows build artifacts with Github Actions

- windows/CMakeLists.txt
- windows/hidapi.rc
- windows/hidapi.vcxproj
- windows/hidapi.vcxproj.filters
> windows: Add .rc

- libusb/hid.c
- pass the actual HID Report descriptor size (from HID descriptor);
- interface_num has to be wIndex, and not as part of wValue for LIBUSB_DT_REPORT request;
TODO:
Resolves: #438
> libusb: fix HID Report descriptor request

- .builds/alpine.yml
- .builds/archlinux.yml
- .builds/fedora-mingw.yml
- .builds/freebsd.yml
- .builds/netbsd.yml
- .builds/openbsd.yml
Check CMake build on:
- Alpine
- Archlinux
- Fedora/mingw64
- FreeBSD
> CI: more CMake build checks

- windows/hidapi_descriptor_reconstruct.c
> Replaced linked list rd_item_byte by buffer array

- .gitignore
Observed generated "configure~" file during build in Ubuntu.
> Add configure~ to .gitignore

- README.md
- hidtest/test.c
Same change as https://github.com/libusb/hidapi/pull/470
> Add hid_exit() to test.c when handle not found

- src/CMakeLists.txt
> fixed CMake problems (#482, #483)

- .github/workflows/builds.yml
> Fixed typo in GitHub workflow

- .github/workflows/builds.yml
- BUILD.md
- HACKING.txt
- README.md
- configure.ac
- hidtest/CMakeLists.txt
- hidtest/test.c
- linux/hid.c
- src/CMakeLists.txt
...and solve the merge conflicts.
> Merge master into get descriptor

- mac/hid.c
I've started getting this recently
> macOS: silence sprintf deprecation

- mac/hid.c
Reference issue: https://github.com/libusb/hidapi/pull/509
> mac: replace sprintf uses with snprintf.

- windows/hidapi_descriptor_reconstruct.c
- windows/test/hid_report_reconstructor_test.c
I didn't notice, that Coverity issues can contain multiple occurrences - so I fixed only the first one. Now I fixed also the second occurence of CID1530054.
> Coverity fix2

- windows/hid.c
> Correct type (int) for printf width specifier

- windows/hid.c
> Fix "Explicit null dereferenced"

- .github/workflows/builds.yml
`refreshenv` stopped working in PowerShell context
> Fix Windows CI

- windows/hidapi_descriptor_reconstruct.h
- windows/hidapi_hidsdi.h
As reported in #630
Fixes: #630
> Fix two C++-Builder 11 issues

- mac/hid.c
> pthread_barrier_wait: properly check the wait condition

- README.md
> Fix Github Builds status badge

- libusb/hid.c
> fix possible null-pointer dereference

- .github/workflows/builds.yml
> Fix Apline CI build
